version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    # volumes:
    #   - ./dynamodb_local_db:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb"
